---
editor_options: 
  markdown: 
    wrap: 72
---

# Introduction

Each chapter of the book is composed of the following three aspects:

1.  An important topic or question in translational bioinformatics

2.  An example of publicly available data (if data is not available
    publicly, only the methodologies will be described)

3.  R code utilizing advanced statistics, machine learning and/or causal
    inference methods

## Topics

The following topics will be covered:

-   Dimensionality reduction
    -   PCA and tSNE
    -   Feature selection and extraction for machine learning

-   Prognostic and Predictive biomarkers

    -    Predictive biomarker identification using interpretative
        machine learning approach.

    -   Prognostic predictions using Bayesian statistics.

-   Benchmarking survival predictions using statistics and machine
    learning

-   Subgroup identification using causal discovery and counterfactual
    modeling

-   Estimand thinking in biomarkers:

    -   ICH E9 addendum on Estimands

    -   Estimands thinking and biomarkers
